server:
  port: 80
wechat:
  appId: 'wx7f3771fd2054a9f9'
  secret: '7218ce3aff8f5af0bc7380f197a2fd0e'
#  我的小号
  userId: 'oP6mj6ieL3u0EO7tuFXeoUkzxR3I'
#  王雅娜
  user2Id: 'oP6mj6rNt2irN9iMleLY89XSlDt0'
  user3Id: 'oP6mj6tGbt0ZVPP5Hbp4x-WxfOno'
#  朋友模板
  templateId: 'b613fZzFj_M4sc7ryGEHlNsrOg5TKzmn4lhVYYOnjRo'
#  单词模板
  template2Id: 'wU7-zd_-LdNdKnScR9XysXEXYDyX7cqlomTCYeJay80'
  district_id: '130304'
  ak: '8HHZ7hXIG05fiCySbCyX6BXAdGwTdllD'
  loveDate: '2023-10-06'
  birthday: '2001-06-25'
  rainbowKey: '892f2034bc3b1070c4c96f2567512689'